### ISSUE TITLE
SWP/THA: 019 - Preparation of Otoliths and other materials use for age estimation

### ISSUE THREAD

**Issue by RobichaudA** [dfo-gulf-science/CADI#66]
**Task Hazard Analysis (THA) Process**
- [ ] Identify all occupations within the Science branch
- [ ] Establish a THA Team (Team Leader, Supervior, Employee, Document Control Person)
- [x] Identify all tasks in **Task Inventory Worksheet - Column A**
- [x] Identify all hazards associated with the tasks in **Task Inventory Worksheet - Column B**
- [ ] Assess risks for each tasks using the **Hazard Assessment Methodology** and provide assessment in **Task Inventory Worksheet - Column C** 
	(Consult with your OHS Advisor for HOIR, first aid logs/records, complaints, workplace inspection reports, SDS, violence in the workplace reports, safety audits, injury statistics, OHS committee observations)
- [ ] Identify control measures for each task in **Task Inventory Worksheet - Column D**
- [ ] Provide, in detail, appropriate control measures for each task in **Task Inventory Worksheet - Column E**
- [ ] Provide date of completion/implementation for each task in **Task Inventory Worksheet - Column F**
- [ ] Provide date of review for each task in **Task Inventory Worksheet - Column G** (where applicable)
- [ ] If training/education is identified as a control measure, an education/training schedule is required

**Critical Task Hazard Analysis Worksheet / Safe Work Procedure (SWP) Process**
- [x] All task rated **6** or greater in the **Task Inventory Worksheet** are considered a critical task and require a **Critical Task Hazard Analysis Worksheet** and a **Safe Work Procedure**
- [x] Using the **Critical Task Hazard Analysis Worksheet - Column A** outline each step of the critical task
- [x] Identify the hazards for each step of the critical task in the **Critical Task Hazard Analysis Worksheet - Column B** 
- [x] Identify the control measures and develop task instructions in **Critical Task Hazard Analysis Worksheet - Column C**
- [x] Develop the **Safe Work Procedure** using the information developped in the **Critical Task Hazard Analysis Worksheet*

**Review/Approvals**
- [ ] Internal review within Science Branch
- [ ] Regional OHS Advisor
- [ ] Branch Director
- [ ] Team Leader presents to OHS Committee
- [ ] Branch Director considers OHS Committee input where applicable
- [ ] Branch Director approves

**Employee Sign-off**
- [ ] Employees sign-off on each tasks that applies to their job (Annex D)
